### ISSUE TITLE
Sites column in Alerts is not showing sites names

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#819] opened 2016-02-19 15:26 UTC
Found in Version: 0.10-pre3

Preconditions:
There is an 'Institution Foo' with several Sites

Navigate to Alerts and create a new alert 'Bar'
Select at least two Sites that belong to 'Institution Foo'
Save alert and observe Alert's listing

Observed:
```#<Site::ActiveRecord_Associations_CollectionProxy:0x0055b7971a9948>``` appears under Sites column in Alert's listing

Expected:
The selected sites names should be displayed under Sites column for created alert

**Comment by anthonyoleary** [comment] 2016-02-22 10:48
I was not able to reproduce this in the latest branch: https://github.com/finddx/cdx/tree/hotfix/anamolie-alert, would it be possible to retest. Thanks.

**Comment by vtiffenberg** [comment] 2016-03-04 19:05
Can't reproduce either. Closing

**Comment by pmallol** [comment] 2016-03-08 17:54
Ok in Version: 0.11-pre7

**Closed** 2016-04-21 20:19 UTC
Labels: alerts, bug, normal, verified
