### ISSUE TITLE
Accessing the report crashes when the samples values are changed

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1966] opened 2023-07-07 19:40 UTC
### Steps to reproduce the error
1. Create a box, transfer it to another institution, confirm the transfer, upload the results, create a report.
2. You'll see that you can access the report normally.
3. Open any sample from the box.   Edit any value, for example the Technician name.
4. Go back to the report and try to open it.  
5. It will crash.

![image](https://github.com/instedd/cdx/assets/25181052/7e1a331c-33eb-4421-9c77-5f77560c3daf)

**Comment by ysbaddaden** [comment] 2023-07-21 10:50
I can't reproduce. It may have been fixed by #1974.

**Comment by leandroradusky** [comment] 2023-07-25 09:11
This error happens because the measured signal is converted to a string when the sample is edited. 

In the last merge with the bugfixes made by @ysbaddaden this:

```
      - if @sample_form.measured_signal
        = f.form_field :measured_signal do
          = f.text_field :measured_signal, readonly: true
```

changed to 

```
      - if @sample_form.measured_signal
        = f.form_field :measured_signal do
          .value= @sample_form.measured_signal
```

This will correct the error automatically?

**Comment by ysbaddaden** [comment] 2023-07-25 15:46
Yes, it won't be sent anymore, so it won't be saved anymore.

**Comment by ysbaddaden** [comment] 2023-07-25 15:47
QA: we didn't fix the existing invalid samples in staging. You must reproduce the edit steps with new samples.

**Closed by ysbaddaden** 2023-07-25 15:46 UTC
Labels: bug

**Comment by sardar-usman** [comment] 2023-08-01 10:40
@leandroradusky It is working fine.
