### ISSUE TITLE
Filters form is not correctly displayed if screen width < 1400

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1280] opened 2021-07-20 15:27 UTC
![image](https://user-images.githubusercontent.com/518152/126351822-6223c852-85ee-47d4-872b-c557bb24761f.png)

**Comment by straight-shoota** [comment] 2022-03-02 12:34
Duplicate of https://github.com/instedd/cdx/issues/1380

**Closed by straight-shoota** 2022-03-02 12:34 UTC
Labels: bug

**Comment by diegoliberman** [comment] 2022-03-02 16:27
Work item deleted in Commit
