### ISSUE TITLE
Institutions can assign samples to other institutions

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1290] opened 2021-07-27 09:39 UTC
An institution can assign samples to a different institution, provided they own them in the first place. 

### Use case
1.- Institution A creates a batch of samples and then distributes those samples among Institutions B, C, and D
2.- Institution B receives a sample, but can't process it and reassigns it to either A, C, or D
--> Can samples be passed on to a third institution? (Re-gifting a gift)

### Edge case
1.- Institution A wrongfully assigns a sample that belongs to Institution B to Institution D
--> Institution A should be able to undo the action. Or should we allow for institutions to send samples back in the system?

**Comment by diegoliberman** [comment] 2021-12-14 19:22
I would delete this issue, as it looks like a duplicate of #1101.  @gbatiston ?

**Comment by gbatiston** [comment] 2021-12-15 06:55
These were supposed to be different tasks, stemming from #1101 but sure, we can close this and let the team create the tasks as they go @diegoliberman :)

**Comment by diegoliberman** [comment] 2021-12-16 12:14
Work item deleted in Commit

**Closed by diegoliberman** 2021-12-16 12:14 UTC
