### ISSUE TITLE
'Add sample/tests' search bar not working for new Encounters

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#605] opened 2015-12-03 18:06 UTC
Found in Version: 0.7-pre7

Preconditions:
There is at least one test uploaded with sample number '1'.

1. Navigate to Tests and click the + button
2. Click on Append sample
3. Type "1" in the search bar and wait for the sample to appear to be selected

4. Click on Add tests and try searching for a test to add

Obtained:
The search does not show either a sample to select and append nor a test to select to add to the new encounter.

Expected:
Sample '1' should appear under the search bar so that it can be appended in the new encounter. Same with tests.

**Comment by asterite** [comment] 2015-12-04 18:01
Closing because it's expected behaviour, samples that belong to another encounter don't show up in test results.

**Comment by pmallol** [comment] 2015-12-18 16:26
Ok in Version: 0.7-pre10

**Closed** 2016-04-21 20:20 UTC
Labels: bug, major, verified
