### ISSUE TITLE
Remove multiple crosses in select 2 combo

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#572] opened 2015-11-26 17:49 UTC
Locations on the site selection.

**Comment by matiasgarciaisaia** [comment] 2015-11-26 17:52
<img width="1158" alt="screen shot 2015-11-26 at 2 50 46 pm" src="https://cloud.githubusercontent.com/assets/5470539/11428729/56d9a4da-944d-11e5-859e-c15e94323976.png">

**Comment by asterite** [comment] 2015-11-26 20:47
Can't reproduce

**Comment by matiasgarciaisaia** [comment] 2015-12-01 19:21
I still see this as of 4a8bb08e5cd4d371b90185912fe8056dca0a2b80. Anyone else?

**Comment by asterite** [comment] 2015-12-01 20:05
Just tried it again, I can't reproduce this on my machine. Also tried with assets precompiled.

**Comment by mmuller** [comment] 2015-12-18 15:22
Ok in version 0.7-pre10

**Comment by pmallol** [comment] 2015-12-18 15:28
Still present in Version: 0.7-pre10

**Comment by spalladino** [comment] 2015-12-18 15:44
This no longer happens in 0.8, since `select2` has been removed from the app. @nekron should we disregard the issue as wontfix?

**Comment by spalladino** [comment] 2015-12-18 15:47
Cherry-picked https://github.com/instedd/cdx/commit/11904ee89d92cc292039e7de0aeb50ded5f2b114 into release/0.7

**Comment by pmallol** [comment] 2016-02-15 18:47
Ok  in Version: 0.7-pre12

**Closed** 2016-04-21 20:20 UTC
Labels: verified
