### ISSUE TITLE
[hierorgs] Tree view for hierarchical sites

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#505] opened 2015-11-09 19:51 UTC
As a user with site management permissions, I want to see a tree view of all the sites that I have access to.

**Comment by nditada** [comment] 2015-11-12 19:49
For reference: https://projects.invisionapp.com/d/main#/console/4103589/115034317/preview

**Comment by nditada** [comment] 2015-12-14 16:53
@bcardiff is this a dupe of another one you were wrapping up?

**Comment by bcardiff** [comment] 2015-12-14 17:34
@nditada I would say it's a dupe of #514 . 

The toggle for "Selection includes all subsites" is not currently implemented. The current behavior is to include all subsites in selection.

**Comment by nditada** [comment] 2015-12-14 18:32
ok, closing this one then.

**Closed** 2016-04-21 20:20 UTC
Labels: verified
