### ISSUE TITLE
Orphan tests view throws server error

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#757] opened 2016-02-12 20:44 UTC
Found in version: 0.7-pre12

Preconditions:
There is a Device 'Foo'
There are Tests associated to the Device 'Foo'

Reproduce steps:
Go to the Device 'Foo' view
Remove the Device 'Foo'
Visit some Test associated to the Device 'Foo'

Actual result:
A server error is thrown

Expected result:
If there are Tests associated to a Device it should not be removed

**Comment by nekron** [comment] 2016-02-15 22:05
Duplicate of #764

**Closed** 2016-02-15 22:05 UTC
Labels: bug, critical, duplicate
