### ISSUE TITLE
500 when viewing test order detail

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/cdx#794] opened 2016-02-18 18:47 UTC
(http://cdx-dev.instedd.org/encounters/1f4f93a8-5ecd-5035-f057-75266fde0c7f?context=edb84496-a0af-9033-0894-514db813f32e

user: vtiffenberg@manas.com.ar pass: 12345678)

OpenSSL::Cipher::CipherError (wrong final block length): app/models/message_encryption.rb:13:in `decrypt' app/models/concerns/entity.rb:66:in `plain_sensitive_data' app/models/encounter.rb:38:in `phantom?' app/models/concerns/entity.rb:114:in `not_phantom?' app/models/blender.rb:256:in `add_entity' app/models/blender.rb:197:in `block in initialize' app/models/blender.rb:197:in `each' app/models/blender.rb:197:in `initialize' app/models/blender.rb:37:in `new' app/models/blender.rb:37:in `load' app/controllers/encounters_controller.rb:132:in `prepare_blender_and_json' app/controllers/encounters_controller.rb:127:in `load_encounter'	Thu Feb 18 2016, 18:44:18.172 UTC

**Comment by bcardiff** [comment] 2016-02-22 16:21
Some encrypted columns contains the string `"Failed"` which can't be decrypted.

```
> select count(*), sensitive_data from encounters group by sensitive_data order by count(*) desc;
+----------+--------------------------------------------------+
| count(*) | sensitive_data                                   |
+----------+--------------------------------------------------+
|      104 | ?e5?M%?V5^??晀                                   |
|       29 | Failed                                           |
```

```
> MessageEncryption.decrypt("Failed")
OpenSSL::Cipher::CipherError: wrong final block length
    from /app/vendor/bundle/ruby/2.2.0/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `final'
```

Although this still happen, mimicing the trace from the server does seem to trigger the issue since there is no "Failed" string in the encounter linked, but it does happen on other encounters / test results in **QA_inst** and **Demo Institution**. @mmuller @pmallol any insight regarding how you reached those?

**Comment by pmallol** [comment] 2016-02-29 14:19
Not really @bcardiff , those tests belong to testings in the past that seem to have been erased.

**Comment by bcardiff** [comment] 2016-02-29 14:37
Sorry @pmallol this should be fixed. The old tests are still in the db. I can't figure how a test with a `Failed` sensitive_data could have been generated. But the the current issue was that the tests where retrieved by `uuid`, the uuid started with a number, and prior https://github.com/instedd/cdx/commit/50d54755ca6c5b2f938f6fc237900a5225bb8684 instead of the test with the corresponding `uuid`, the test with that number as `id` was returned.

You should be able to load all the tests now.

**Comment by pmallol** [comment] 2016-03-03 18:56
Could not reproduce, test orders can be viewed ok in  Version: 0.11-pre6

**Closed** 2016-04-21 20:04 UTC
Labels: bug, major, verified
