### ISSUE TITLE
Migration of new fields for existing batches (in production)

### ISSUE THREAD

**Issue by leandroradusky** [instedd/cdx#1864] opened 2023-01-24 10:04 UTC
With respect to the columns that will be appended in the `Batch` entity: they have this information available on a spreadsheet for the existing batches. When we implement the data migration, we have to map these columns for the existing batches taking this spreadsheet as a reference for one time only.

(Alternatively, they will have to go batch by batch defining it for the existent batches, but was mentioned that this migration can be done). 

For new batches they will define the full information.

**Comment by ysbaddaden** [comment] 2023-02-15 14:32
Closing as duplicate of #1922

**Closed by ysbaddaden** 2023-02-15 14:32 UTC
Labels: task

**Comment by diegoliberman** [comment] 2023-02-15 16:19
Work item deleted in Commit
