### ISSUE TITLE
Scope users by the selected site

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#515] opened 2015-11-12 19:20 UTC
Display the list of users scoping by the selected site. This means, only display the users that belongs to a role inside the selected institution or site.

**Comment by spalladino** [comment] 2015-11-13 22:24
Is this a duplicate of #507?

**Comment by nekron** [comment] 2015-11-23 14:30
#507 is the user story, this is a single task of just scoping the list that we have. It will require a couple more changes to actually complete the whole story, i.e. roles or filters.

**Comment by mmuller** [comment] 2016-03-07 16:39
Ok in version 0.11-pre6

**Closed** 2016-04-21 20:20 UTC
Labels: verified
