### ISSUE TITLE
Description of select combo is overlayed by text cursor in new alert

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#903] opened 2016-02-26 15:34 UTC
Found in Version: 0.11-pre4

Navigate to Alerts
Click on button to create a new Alert
Click on 'All' in SITES selector

Obtained:
A text cursor overlays the 'All' description. The description disappears when typing
![screen shot 2016-02-26 at 12 32 14 pm](https://cloud.githubusercontent.com/assets/9214460/13356654/423bdb30-dc85-11e5-9d7d-49a4178721db.png)

Expected:
The text cursor should not overlay the field's description. It should appear before like other fields such as NAME or DESCRIPTION

**Comment by anthonyoleary** [comment] 2016-02-29 10:28
I tried with the latest code, https://github.com/JedWatson/react-select/ , but for some reason that caused the drop downs not to work, also tried to use the react-js.css that comes with the library but that make no difference.
The problem is in the  react-select library. I can do more investigation.

**Comment by bcardiff** [comment] 2016-02-29 14:14
This should be fixed with css only. The cursor is aligned with the other inputs. React-select is rendering manually the placeholder, hence my assumption that it is just a css thing.

**Comment by pmallol** [comment] 2016-03-08 17:51
Ok in Version: 0.11-pre7

**Closed** 2016-04-21 20:20 UTC
Labels: alerts, bug, minor, verified
